name: nim_test

on: [push]

jobs:
  test:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - ubuntu-16.04
          # - windows-latest
          - macos-latest

    env:
      NIM_VERSION: stable

    steps:
    - uses: actions/checkout@v1
    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-${{ env.NIM_VERSION }}
    - name: Cache nimble
      id: cache-nimble
      uses: actions/cache@v1
      with:
        path: ~/.nimble
        key: ${{ runner.os }}-nimble-${{ hashFiles('*.nimble') }}
    # - name: Setup Nim environment
    #   uses: jiro4989/setup-nim-action@master
    #   with:
    #     nim-version: ${{ env.NIM_VERSION }}
    - name: Install Nim
      # if: steps.cache-choosenim.outputs.cache-hit != 'true' || steps.cache-nimble.outputs.cache-hit != 'true'
      env:
        CHOOSENIM_CHOOSE_VERSION: ${{ env.NIM_VERSION }}
      run: |
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y
    - name: Run test
      run: |
        export PATH=~/.nimble/bin:$PATH
        echo $PATH
        nimble test -y
